name: Ghb token
description: GHB token for modules
author: Mihail Sahatchiev
inputs:
  token:
    required: true
    description: secrets.GHB_TOKEN
  name:
    default: user
    description: user
  email:
    default: something@something.com
    description: Author email.

runs:
  using: node12
  main: action.js